version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: shamir_user
      POSTGRES_PASSWORD: shamir_pass
      POSTGRES_DB: shamir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamir_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    healthcheck:
      test: ["CMD", "nats", "account", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/servers/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shamir_user
      DB_PASSWORD: shamir_pass
      DB_NAME: shamir_db
      NATS_URL: nats://nats:4222
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - ./:/app
    command: ["./main"]

volumes:
  postgres_data: